@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

annotation FunctionalInterface << annotation >>
class PhoneContainsSequencePredicate
interface Predicate<T> << interface >>

PhoneContainsSequencePredicate  -[#008200,dashed]-^  Predicate
Predicate                       -[#999900,dotted]-  FunctionalInterface
@enduml
