@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

annotation FunctionalInterface << annotation >>
interface Predicate<T> << interface >>
class UsernameContainsKeywordsPredicate

Predicate                          -[#999900,dotted]-  FunctionalInterface
UsernameContainsKeywordsPredicate  -[#008200,dashed]-^  Predicate
@enduml
